### ISSUE TITLE
Not working in GNOME 3.34

### ISSUE THREAD

**Issue by LuSo58** [AlexPoilrouge/NordVPN-connect#10] opened 2019-09-21 07:52 UTC
Immediately throws an error after being enabled.

![Screenshot from 2019-09-21 09-49-22](https://user-images.githubusercontent.com/22314804/65370090-81d40f00-dc55-11e9-8d5a-9a082ca2e318.png)

**Comment by rodolpheh** [comment] 2019-09-22 19:05
I can confirm this issue on Gnome 3.34, Arch Linux with 5.3.1 Linux kernel.

**Comment by AlexPoilrouge** [comment] 2019-09-22 22:12
I have acknowledge this issue.
Sadly I do now yet how to fix this.

Here are the code part that triggersthe bug under gnome 3.34:

**extension.js**
```
...
const SubMenus= Me.imports.subMenus;
...
class NVPNMenu extends PanelMenu.Button{
...
_init(){
...
    this._submenuPlaces= new PlacesMenu();
    
    this.menu.addMenuItem(this._submenuPlaces);

    this._submenuPlaces.select_callback(this._place_menu_new_selection.bind(this));
...
}
```

**extension.js**
```
...
class PlacesMenu extends PopupMenu.PopupSubMenuMenuItem{
...
    select_callback(func= null){
      this.select_cb= func;
    }
...
}
```

For some reason, even though the object PlacesMenu is constructed and initialized, the reference to the `select_callback` method remains `undefined`.
This is a very odd behavior, and I have yet to determine if this is a normal behavior within the new gnome 3.34 extension system.
A quick research doesn't bring up anything helpful on the matter.
I don't yet have the time to dive into this too much right now.
Any hint, suggestion, information on the matter would be very welcome.

**Comment by AlexPoilrouge** [comment] 2019-09-22 23:34
Okay, I managed to find a fix for gnome 3.34 after all.

I've pushed this emergency fix on the `master` branch.

A few notable bugs might have slip through, since I did this a bit in a rush. Please report if you find any.

Although, the code will have to be cleansed and refactorised before I push the fix to the gnome-extension website. So this will not happen before a few weeks, due to time constraints.

Thank you!

**Comment by LuSo58** [comment] 2019-09-23 09:14
Installed on Arch via the AUR git package and it seems to work just as before. Disconnecting and switching between servers works.

The extension debugger says, the extension didn't generate any errors.

**Comment by rodolpheh** [comment] 2019-09-23 12:13
Installed on Arch via the AUR git package, I get an error :
```
Error: Type Gjs_PlacesMenu is already registered
```
Thank you for your work. It doesn't work yet but it shows your implication :)

**Comment by LuSo58** [comment] 2019-09-23 12:18
I'd guess, that that's caused by some other extension registering the same type. I have the same gnome version, and it works fine., perhaps try to disable all extensions but the NordVPN connect and repeat adding an extension and reloading gnome, until it displays this error.

Providing of course, this error disappears after being the only one enabled.

**Comment by AlexPoilrouge** [comment] 2019-09-23 19:40
@rodolpheh I think @LuSo58  is right.
And there's a chance I've also found the culprit.
On the off chance, would you happen to be using this [extension as well](https://extensions.gnome.org/extension/8/places-status-indicator/)?

I also use this extension, but the reason I didn't get the error is because it only seems to occur when my extension is installed globally (what the AUR install does) but not locally (per user).

It happens that both the extensions uses an object referenced under the name "PlacesMenu".
Since their extension is a bit more fitting for the use of that name, I'm willing to concede it to them and rename my object 😛

Well, I guess this was your issue, but I might be mistaken. In case it was, I've updated the `master` branch and the AUR package.

Would you please confirm or infirm the fix on your end?

Thanks for reporting.

**Comment by rodolpheh** [comment] 2019-09-23 21:21
Sorry for the delay, i'm on a business travel and couldn't answer before. I do use the Places Indicator extension and disabling it made your extension work again. I was suspecting a conflict with another extension as @LuSo58  suggested but couldn't verify it as I was using my computer as a display on a convention. Anyway, it seems "fixed" for now since Places Indicator is the only extension conflicting with NordVPN on my setup. Thank you for your work.

**Comment by rodolpheh** [comment] 2019-09-23 21:23
The latest AUR git package completely solved my issue regarding the conflict with the Places Indicator extension. :tada:

**Comment by AlexPoilrouge** [comment] 2019-09-25 12:34
A Gnome-shell 3.34 version of the extension is now available on each of the 3 release medium (Github, AUR, and the Gnome-extension website).

I believe/hope these release are stable enough to close this issue.

Thanks fellas for the feedback!

**Closed by AlexPoilrouge** 2019-09-25 12:34 UTC
Labels: bug
